using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("5.0.0.0")]
[assembly: AssemblyFileVersionAttribute("5.0.0.0")]
[assembly: AssemblyCopyrightAttribute("Copyright © MVC Contrib 2007-2013")]
[assembly: AssemblyProductAttribute("MVCContrib")]
[assembly: AssemblyCompanyAttribute("MVC Contrib")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("5.0.0.0")]

